# Generated by Django 2.2.dev20180903084355 on 2018-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0003_notice_notice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_press',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
