# Generated by Django 2.2.dev20180903084355 on 2018-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0004_book_book_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
