# Generated by Django 2.2.dev20180903084355 on 2018-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0007_comment_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_receiver_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='order_receiver_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_complete_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
