# Generated by Django 2.2.dev20180903084355 on 2018-09-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0008_auto_20180929_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
