from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('index/', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('adminLogin', views.adminLogin, name='administrator_Login'),
    path('getbook', views.getbook, name='getbook'),
    path('getNotice', views.getNotice, name='getNotice'),
    path('getRankList',views.getRankList,name='getRankList'),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('newBook/', views.newBook, name="newBook"),
    path('book_detail/', views.book_detail, name="book_detail"),
    path('admin', views.BookManageHTML, name="admin"),
    path('addBook/', views.add_book, name="addBook"),
    path('base/', views.base, name="base"),
    path('test/', views.test, name="test"),
    path('book_manage/', views.book_manage, name="BookManage"),
    path('UserManage/', views.UserManage, name="UserManage"),
    path('OrderManage/', views.OrderManage, name="OrderManage"),
    path('NoticeManage/', views.NoticeManage, name="NotiveMange"),
    path('AccountManage/', views.AccountManage, name="AccountManage"),
    path('ConmentManage/', views.ConmentManage, name="Commentmange"),
    path('manage_base/', views.manage_base, name="manage_base"),
    path('order_content', views.order_content, name="order_content"),
    path('cart', views.cart, name="cart"),
    path('order', views.order, name="order"),
    path('BookManage/', views.BookManageHTML, name="BookManage"),
    path('addNotice', views.addNotice, name="addNotice"),
    path('deleteNotice', views.deleteNotice, name="deleteNotice"),
    path('queryBook', views.queryBook, name="queryBook"),
    path('modifyBook/', views.modifyBook, name="modifyBook"),
    path('queryComment/', views.queryComment, name="queryComment"),
    path('deleteComment/', views.deleteComment, name="deleteComment"),
    path('queryUser/', views.queryUser, name="queryUser"),
    path('changeUserFreezeState/', views.changeUserFreezeState, name="changeUserFreezeState"),
    path('queryOrder', views.queryOrder, name="queryOrder"),
    path('deleteOrder', views.deleteOrder, name="deleteOrder"),
    path('deliverGoods', views.deliverGoods, name='deliverGoods'),

]
